name: Deploy to server

on: push

jobs:
  first_job:
    name: Tutorial CodigoFacilito action
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Workin dir
        id: step_1
        run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT
      
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"
  
  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}
    steps:
      - name: Hola Mundo
        run: echo "$SALIDA"