name: Deploy to server

on: push

jobs:
  first_job:
    name: Tutorial CodigoFacilito action
    runs-on: ubuntu-latest

    env:
      name: CodigoFacilito

    steps:
      - name: Workin dir
        run: ls -al
      
      - name: Action
        uses: actions/checkout@v4
      
      - name: Working dir after action
        run: ls -al
  
  second_job:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo"